### ISSUE TITLE
How does saddle achieve bin operator vectorization?

### ISSUE THREAD

**Issue by tnielens** [pityka/saddle#313]
A few questions come up when browsing saddle doc. 

How does saddle achieve bin operator vectorization? What is the difference between regular operators and macro operators?
The original documentation has a short section on the topic without much explanation: https://saddle.github.io/doc/quickstart.html#a-note-on-optimization

I didn't find these answers easily/at all in the current doc. A doc section on this topic would be great.

**Comment by pityka** [comment]
the word 'vectorization'  is a bit misleading. There is no SIMD or whatsoever in saddle. 

The original documentation refers to that the API is more convenient because you can write `a + b` instead of something like

```
var i = 0 
while (i < n) {
a(0) + b(0)
i+=1
}
```

What saddle brings in over plain scala collections is that 1 )it avoids boxing whenever possible 2) the API is more terse 

In certain cases the non-macro binary operators box, while the macro based ones do not. 

I will add a section on this matter in the docs which I maintain.

If you need real vectorization then you may want to take a look at https://pityka.github.io/lamp/docs/usage_overview/#n-dimensional-arrays-for-numeric-code

**Comment by tnielens** [comment]
Thanks!

At some point I also wondered if the macro operators aimed at hotspot auto-vectorization referred in 
https://cr.openjdk.java.net/~vlivanov/talks/2017_Vectorization_in_HotSpot_JVM.pdf

That feature is referenced in this article: 
https://blogs.oracle.com/javamagazine/post/java-vector-api-simd

**Comment by pityka** [comment]
No, not at all. Macros are solely there to prevent Scala from boxing. 

The java vector API is not used in saddle. As far as I know the new java vector api is not supported on older jvms and neither available in scala-js. At this point I would like to keep saddle-core to run on all these platforms (I will add scala-native support later). 

It could be possible to implement the Vec[T] trait in terms of the java vector api and put that into a separate module. I did not explore this path.

Some options currently implemented which provide good performance:
- saddle-linalg in https://github.com/pityka/saddle/tree/master/saddle-linalg/src/main/scala/saddle/linalg uses LAPACK and BLAS and does so by keeping the data on the heap. 
- pityka/lamp, this piggybacks on pytorch, gives support for GPUs and copies data out of the jvm into off-heap memory. As such it also supports huge arrays (longer than what is indexable with 32 bit integers).

**Comment by tnielens** [comment]
Ah my second link was confusing, but I was referring to the auto-vectorization features of hotspot in jdk8/9 that existed before the Vector api. That is, simple for loops are vectorized by hotspot at jit compilation. But I assume that feature is too brittle for a library to target.

**Comment by tnielens** [comment]
Closing this one as the main occurrence of "vectorized" in the documentation was removed by @pityka .
